import "./globals.css";

import Navbar  from "~/components/Navbar";
import Footer from "../components/Footer"

export const metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className = "bg-gray-900 text-white flex flex-col min-h-screen">
        <Navbar />{}

        <main className = "max-w-4xl mx-auto p-4 flex-grow">
          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}
